name: CI

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/ci.yml"
      - "src/**"
      - "src-tauri/**"
      - "package.json"
  pull_request:
    branches:
      - main
    paths:
      - "src/**"
      - "src-tauri/**"
      - "package.json"

jobs:
  build:
    strategy:
      matrix:
        platform:
          - os: ubuntu-24.04-arm
            target: aarch64-unknown-linux-gnu
            name: Linux ARM64
            artifact-name: linux-arm64
            artifact-path: |
              src-tauri/target/aarch64-unknown-linux-gnu/release/**/*.deb
              src-tauri/target/aarch64-unknown-linux-gnu/release/**/*.rpm
              src-tauri/target/aarch64-unknown-linux-gnu/release/**/*.AppImage
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            name: Windows x86_64
            artifact-name: Windows_x64
            artifact-path: |
              src-tauri/target/release/bundle/**/*.exe
              src-tauri/target/release/bundle/**/*.msi

    runs-on: ${{ matrix.platform.os }}
    name: Build ${{ matrix.platform.name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt-get install -y \
            pkg-config \
            libwebkit2gtk-4.1-dev \
            libgtk-3-dev \
            libssl-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            xdg-utils

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: src-tauri

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Build Tauri App
        run: bun tauri build ${{ runner.os == 'Linux' && format('--target {0}', matrix.platform.target) || '' }} --debug

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform.artifact-name }}
          path: ${{ matrix.platform.artifact-path }}